# Site settings
title: Islampedia
email:
description: >
  Ensiklopedia Islam
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.islampedia.id" # the base hostname & protocol for your site

twitter_username:
github_username:
google_analytic_id: UA-74093646-1
disqus_name: islampedia

permalink: /:categories/:title
paginate: 5
paginate_path: /page/:num

# jekyll seo tag settings
logo: assets/images/search-icon-black.png
# author:
#   twitter: jekyllrb
# twitter:
#   username: jekyllrb

# Build settings
markdown: kramdown
sass:
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
